spring:
  application:
#服务名
    name: eureka-provider
#服务端口号
server:
  port: 9090
#eureka 配置：设置服务注册中心地址，指向另一个注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
