spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
           uri: ${config.repo.uri:https://github.com/sq1990/springcloud}
           searchPaths: config-repo
      label: master
  profiles:
    active: dev
server:
  port: 9092

